### ISSUE TITLE
What is checkpoint

### ISSUE THREAD

**Issue by darthnithin** [zohairajmal/forza4selfdrive#2]
when i ran it it created a file called "checkpoint" with this:
```
model_checkpoint_path: "C:\\Users\\zohai\\Desktop\\SelfDriving Car Project\\model_alexnet-500"
all_model_checkpoint_paths: "C:\\Users\\zohai\\Desktop\\SelfDriving Car Project\\model_alexnet-500"
```
what is it and what should those directeries be going to.

**Comment by zohairajmal** [comment]
It was a local file which was the checkpoint for my computer. I have removed the file so you can start your own trianing.
